model_7_24_5 = [
    [('sep_conv_5x5', 0), ('dil_conv_5x5', 1), ('sep_conv_5x5', 0), ('skip_connect', 2), ('sep_conv_5x5', 2),
     ('skip_connect', 3), ('dil_conv_5x5', 3), ('dil_conv_5x5', 4)],
    [('sep_conv_5x5', 0), ('skip_connect', 1), ('skip_connect', 1), ('sep_conv_5x5', 2), ('sep_conv_3x3', 1),
     ('dil_conv_3x3', 3), ('sep_conv_3x3', 2), ('sep_conv_3x3', 4)],
    [('sep_conv_5x5', 0), ('skip_connect', 1), ('skip_connect', 1), ('dil_conv_5x5', 2), ('dil_conv_3x3', 1),
     ('sep_conv_5x5', 3), ('dil_conv_3x3', 3), ('sep_conv_5x5', 4)],
    [('sep_conv_5x5', 0), ('skip_connect', 1), ('sep_conv_5x5', 0), ('skip_connect', 1), ('sep_conv_5x5', 0),
     ('sep_conv_5x5', 3), ('sep_conv_3x3', 1), ('dil_conv_5x5', 4)],
    [('sep_conv_3x3', 0), ('max_pool_3x3', 1), ('dil_conv_3x3', 0), ('skip_connect', 1), ('dil_conv_5x5', 0),
     ('dil_conv_3x3', 1), ('sep_conv_5x5', 1), ('sep_conv_3x3', 4)],
    [('skip_connect', 0), ('sep_conv_5x5', 1), ('skip_connect', 1), ('sep_conv_3x3', 2), ('sep_conv_5x5', 0),
     ('sep_conv_5x5', 2), ('sep_conv_5x5', 2), ('dil_conv_5x5', 3)],
    [('sep_conv_5x5', 0), ('skip_connect', 1), ('sep_conv_5x5', 1), ('skip_connect', 2), ('sep_conv_5x5', 1),
     ('sep_conv_3x3', 2), ('sep_conv_5x5', 0), ('dil_conv_5x5', 3)],
    [('dil_conv_5x5', 0), ('skip_connect', 1), ('dil_conv_3x3', 0), ('skip_connect', 1), ('sep_conv_5x5', 2),
     ('dil_conv_3x3', 3), ('dil_conv_3x3', 0), ('dil_conv_3x3', 3)],
    [('dil_conv_5x5', 0), ('skip_connect', 1), ('skip_connect', 1), ('dil_conv_3x3', 2), ('sep_conv_5x5', 0),
     ('sep_conv_3x3', 1), ('sep_conv_5x5', 1), ('dil_conv_5x5', 4)],
    [('skip_connect', 0), ('sep_conv_3x3', 1), ('sep_conv_5x5', 0), ('skip_connect', 2), ('dil_conv_3x3', 1),
     ('dil_conv_3x3', 2), ('dil_conv_3x3', 0), ('sep_conv_5x5', 2)],
    [('skip_connect', 0), ('sep_conv_3x3', 1), ('skip_connect', 0), ('sep_conv_5x5', 2), ('dil_conv_5x5', 0),
     ('sep_conv_3x3', 2), ('sep_conv_3x3', 2), ('sep_conv_3x3', 4)],
    [('skip_connect', 0), ('sep_conv_5x5', 1), ('dil_conv_3x3', 1), ('skip_connect', 2), ('sep_conv_3x3', 2),
     ('dil_conv_5x5', 3), ('dil_conv_3x3', 1), ('sep_conv_5x5', 3)],
    [('skip_connect', 0), ('dil_conv_3x3', 1), ('skip_connect', 1), ('dil_conv_5x5', 2), ('sep_conv_5x5', 0),
     ('sep_conv_3x3', 2), ('dil_conv_5x5', 0), ('sep_conv_3x3', 1)],
    [('sep_conv_5x5', 0), ('skip_connect', 1), ('dil_conv_3x3', 1), ('skip_connect', 2), ('sep_conv_5x5', 0),
     ('sep_conv_5x5', 1), ('sep_conv_5x5', 0), ('sep_conv_5x5', 1)],
    [('skip_connect', 0), ('sep_conv_3x3', 1), ('sep_conv_3x3', 0), ('skip_connect', 2), ('dil_conv_5x5', 1),
     ('sep_conv_3x3', 3), ('dil_conv_3x3', 0), ('sep_conv_3x3', 1)],
    [('sep_conv_5x5', 0), ('skip_connect', 1), ('dil_conv_3x3', 0), ('skip_connect', 2), ('sep_conv_5x5', 0),
     ('sep_conv_5x5', 1), ('dil_conv_3x3', 1), ('dil_conv_5x5', 3)],
    [('skip_connect', 0), ('sep_conv_3x3', 1), ('sep_conv_5x5', 1), ('skip_connect', 2), ('sep_conv_3x3', 1),
     ('sep_conv_5x5', 2), ('sep_conv_3x3', 2), ('dil_conv_5x5', 3)],
    [('dil_conv_3x3', 0), ('skip_connect', 1), ('skip_connect', 0), ('dil_conv_5x5', 1), ('sep_conv_3x3', 0),
     ('dil_conv_5x5', 2), ('dil_conv_3x3', 1), ('sep_conv_5x5', 4)],
    [('skip_connect', 0), ('sep_conv_5x5', 1), ('skip_connect', 0), ('sep_conv_5x5', 1), ('sep_conv_3x3', 0),
     ('dil_conv_5x5', 3), ('dil_conv_3x3', 1), ('sep_conv_3x3', 3)],
    [('skip_connect', 0), ('sep_conv_3x3', 1), ('dil_conv_5x5', 1), ('skip_connect', 2), ('sep_conv_5x5', 1),
     ('sep_conv_3x3', 2), ('dil_conv_3x3', 0), ('dil_conv_5x5', 3)]]

# 77分的模型
model_score_77 = [
    [('sep_conv_5x5', 0), ('dil_conv_5x5', 1), ('sep_conv_5x5', 0), ('dil_conv_5x5', 2), ('skip_connect', 2),
     ('dil_conv_3x3', 3), ('max_pool_3x3', 3), ('dil_conv_5x5', 4)],
    [('sep_conv_5x5', 0), ('skip_connect', 1), ('dil_conv_5x5', 1), ('skip_connect', 2), ('dil_conv_3x3', 2),
     ('sep_conv_3x3', 3), ('dil_conv_5x5', 2), ('sep_conv_5x5', 4)],
    [('skip_connect', 0), ('dil_conv_5x5', 1), ('dil_conv_3x3', 1), ('skip_connect', 2), ('dil_conv_5x5', 1),
     ('sep_conv_5x5', 2), ('sep_conv_3x3', 2), ('sep_conv_5x5', 4)],
    [('skip_connect', 0), ('dil_conv_5x5', 1), ('dil_conv_5x5', 0), ('skip_connect', 1), ('dil_conv_5x5', 0),
     ('dil_conv_3x3', 2), ('dil_conv_5x5', 2), ('dil_conv_3x3', 4)],
    [('skip_connect', 0), ('dil_conv_5x5', 1), ('sep_conv_5x5', 1), ('skip_connect', 2), ('sep_conv_3x3', 0),
     ('dil_conv_5x5', 1), ('sep_conv_5x5', 2), ('dil_conv_5x5', 3)],
    [('skip_connect', 0), ('sep_conv_5x5', 1), ('dil_conv_5x5', 1), ('skip_connect', 2), ('dil_conv_3x3', 0),
     ('dil_conv_3x3', 1), ('sep_conv_3x3', 1), ('sep_conv_5x5', 2)],
    [('skip_connect', 0), ('sep_conv_5x5', 1), ('sep_conv_5x5', 1), ('skip_connect', 2), ('sep_conv_5x5', 0),
     ('sep_conv_5x5', 3), ('dil_conv_5x5', 1), ('dil_conv_5x5', 3)],
    [('skip_connect', 0), ('dil_conv_3x3', 1), ('dil_conv_3x3', 0), ('skip_connect', 1), ('dil_conv_3x3', 1),
     ('sep_conv_5x5', 2), ('sep_conv_5x5', 0), ('dil_conv_5x5', 4)],
    [('sep_conv_3x3', 0), ('skip_connect', 1), ('sep_conv_5x5', 1), ('skip_connect', 2), ('sep_conv_3x3', 2),
     ('sep_conv_5x5', 3), ('dil_conv_3x3', 0), ('sep_conv_3x3', 1)],
    [('skip_connect', 0), ('dil_conv_3x3', 1), ('dil_conv_5x5', 0), ('skip_connect', 2), ('dil_conv_5x5', 0),
     ('sep_conv_5x5', 3), ('dil_conv_3x3', 2), ('sep_conv_3x3', 4)],
    [('skip_connect', 0), ('sep_conv_3x3', 1), ('dil_conv_5x5', 0), ('skip_connect', 2), ('dil_conv_3x3', 0),
     ('sep_conv_3x3', 3), ('dil_conv_3x3', 2), ('dil_conv_5x5', 4)],
    [('skip_connect', 0), ('dil_conv_5x5', 1), ('dil_conv_3x3', 1), ('skip_connect', 2), ('sep_conv_3x3', 1),
     ('dil_conv_5x5', 2), ('dil_conv_5x5', 1), ('sep_conv_3x3', 2)],
    [('skip_connect', 0), ('sep_conv_3x3', 1), ('dil_conv_5x5', 0), ('skip_connect', 2), ('sep_conv_3x3', 1),
     ('dil_conv_3x3', 3), ('sep_conv_5x5', 2), ('dil_conv_5x5', 4)],
    [('sep_conv_3x3', 0), ('sep_conv_3x3', 1), ('sep_conv_5x5', 0), ('skip_connect', 1), ('skip_connect', 0),
     ('dil_conv_3x3', 3), ('sep_conv_5x5', 0), ('dil_conv_3x3', 3)],
    [('sep_conv_3x3', 0), ('skip_connect', 1), ('dil_conv_5x5', 0), ('skip_connect', 2), ('dil_conv_3x3', 0),
     ('sep_conv_3x3', 2), ('sep_conv_5x5', 2), ('dil_conv_3x3', 4)],
    [('dil_conv_3x3', 0), ('skip_connect', 1), ('sep_conv_5x5', 0), ('skip_connect', 1), ('dil_conv_5x5', 1),
     ('dil_conv_5x5', 2), ('sep_conv_3x3', 1), ('sep_conv_3x3', 3)],
    [('skip_connect', 0), ('sep_conv_3x3', 1), ('sep_conv_3x3', 0), ('skip_connect', 1), ('sep_conv_3x3', 1),
     ('sep_conv_3x3', 2), ('dil_conv_3x3', 0), ('sep_conv_5x5', 2)],
    [('sep_conv_5x5', 0), ('skip_connect', 1), ('skip_connect', 0), ('sep_conv_3x3', 1), ('sep_conv_3x3', 0),
     ('sep_conv_3x3', 2), ('sep_conv_3x3', 0), ('dil_conv_5x5', 2)],
    [('dil_conv_5x5', 0), ('skip_connect', 1), ('dil_conv_5x5', 1), ('skip_connect', 2), ('sep_conv_3x3', 0),
     ('dil_conv_5x5', 2), ('sep_conv_3x3', 1), ('dil_conv_3x3', 2)],
    [('sep_conv_5x5', 0), ('skip_connect', 1), ('skip_connect', 0), ('sep_conv_3x3', 1), ('dil_conv_5x5', 0),
     ('dil_conv_3x3', 1), ('dil_conv_3x3', 1), ('sep_conv_3x3', 2)]]

# 10个模型中最好的网络
model_7_30 = [[('sep_conv_3x3', 0), ('sep_conv_5x5', 1), ('sep_conv_5x5', 1), ('sep_conv_5x5', 2), ('sep_conv_5x5', 2),
               ('skip_connect', 3), ('dil_conv_5x5', 3), ('skip_connect', 4)],
              [('dil_conv_5x5', 0), ('skip_connect', 1), ('skip_connect', 1), ('sep_conv_5x5', 2), ('sep_conv_5x5', 1),
               ('dil_conv_5x5', 3), ('sep_conv_5x5', 3), ('dil_conv_5x5', 4)],
              [('skip_connect', 0), ('dil_conv_5x5', 1), ('skip_connect', 1), ('sep_conv_5x5', 2), ('dil_conv_3x3', 1),
               ('sep_conv_5x5', 3), ('sep_conv_5x5', 1), ('sep_conv_5x5', 3)],
              [('dil_conv_5x5', 0), ('max_pool_3x3', 1), ('skip_connect', 0), ('dil_conv_5x5', 1), ('sep_conv_5x5', 0),
               ('dil_conv_5x5', 1), ('dil_conv_5x5', 0), ('dil_conv_5x5', 1)],
              [('skip_connect', 0), ('sep_conv_3x3', 1), ('skip_connect', 0), ('dil_conv_5x5', 2), ('dil_conv_5x5', 1),
               ('dil_conv_5x5', 2), ('dil_conv_5x5', 2), ('sep_conv_5x5', 4)],
              [('sep_conv_5x5', 0), ('skip_connect', 1), ('dil_conv_5x5', 0), ('skip_connect', 2), ('dil_conv_5x5', 1),
               ('dil_conv_3x3', 2), ('sep_conv_3x3', 2), ('dil_conv_3x3', 3)],
              [('dil_conv_5x5', 0), ('max_pool_3x3', 1), ('dil_conv_3x3', 0), ('skip_connect', 2), ('dil_conv_5x5', 0),
               ('dil_conv_5x5', 1), ('dil_conv_5x5', 0), ('sep_conv_3x3', 4)],
              [('sep_conv_3x3', 0), ('skip_connect', 1), ('dil_conv_5x5', 0), ('skip_connect', 2), ('sep_conv_5x5', 0),
               ('dil_conv_3x3', 1), ('sep_conv_3x3', 0), ('dil_conv_5x5', 1)],
              [('skip_connect', 0), ('dil_conv_5x5', 1), ('skip_connect', 1), ('sep_conv_5x5', 2), ('sep_conv_5x5', 2),
               ('sep_conv_3x3', 3), ('sep_conv_5x5', 1), ('dil_conv_3x3', 4)],
              [('dil_conv_3x3', 0), ('skip_connect', 1), ('sep_conv_3x3', 0), ('skip_connect', 2), ('sep_conv_5x5', 1),
               ('sep_conv_5x5', 3), ('dil_conv_5x5', 3), ('sep_conv_5x5', 4)],
              [('sep_conv_5x5', 0), ('skip_connect', 1), ('skip_connect', 1), ('dil_conv_3x3', 2), ('dil_conv_3x3', 0),
               ('dil_conv_5x5', 1), ('dil_conv_3x3', 0), ('sep_conv_3x3', 1)],
              [('sep_conv_3x3', 0), ('skip_connect', 1), ('dil_conv_3x3', 1), ('skip_connect', 2), ('sep_conv_5x5', 0),
               ('sep_conv_3x3', 1), ('dil_conv_5x5', 0), ('dil_conv_5x5', 1)],
              [('skip_connect', 0), ('sep_conv_5x5', 1), ('sep_conv_5x5', 1), ('skip_connect', 2), ('dil_conv_3x3', 0),
               ('sep_conv_5x5', 1), ('dil_conv_3x3', 2), ('dil_conv_3x3', 3)],
              [('dil_conv_5x5', 0), ('skip_connect', 1), ('dil_conv_5x5', 0), ('skip_connect', 2), ('dil_conv_3x3', 1),
               ('sep_conv_3x3', 2), ('dil_conv_5x5', 0), ('dil_conv_5x5', 3)],
              [('skip_connect', 0), ('dil_conv_3x3', 1), ('sep_conv_3x3', 1), ('skip_connect', 2), ('sep_conv_5x5', 0),
               ('dil_conv_5x5', 1), ('sep_conv_5x5', 1), ('sep_conv_5x5', 4)],
              [('sep_conv_3x3', 0), ('skip_connect', 1), ('skip_connect', 0), ('sep_conv_5x5', 1), ('dil_conv_3x3', 0),
               ('sep_conv_5x5', 2), ('sep_conv_5x5', 0), ('sep_conv_5x5', 2)],
              [('sep_conv_3x3', 0), ('skip_connect', 1), ('skip_connect', 1), ('dil_conv_5x5', 2), ('sep_conv_3x3', 1),
               ('sep_conv_3x3', 2), ('dil_conv_3x3', 0), ('sep_conv_3x3', 2)],
              [('sep_conv_3x3', 0), ('skip_connect', 1), ('sep_conv_5x5', 0), ('skip_connect', 1), ('dil_conv_5x5', 2),
               ('sep_conv_5x5', 3), ('dil_conv_3x3', 1), ('sep_conv_5x5', 4)],
              [('skip_connect', 0), ('sep_conv_5x5', 1), ('skip_connect', 0), ('dil_conv_3x3', 2), ('sep_conv_3x3', 0),
               ('sep_conv_3x3', 2), ('dil_conv_3x3', 0), ('dil_conv_5x5', 2)],
              [('dil_conv_5x5', 0), ('skip_connect', 1), ('sep_conv_5x5', 0), ('skip_connect', 1), ('sep_conv_3x3', 0),
               ('sep_conv_3x3', 2), ('dil_conv_5x5', 0), ('sep_conv_5x5', 1)]]

# 100个网络中最好的
model_7_31 = [[('sep_conv_5x5', 0), ('sep_conv_3x3', 1), ('sep_conv_5x5', 0), ('sep_conv_5x5', 2), ('dil_conv_5x5', 2),
               ('skip_connect', 3), ('dil_conv_5x5', 2), ('skip_connect', 4)],
              [('sep_conv_5x5', 0), ('skip_connect', 1), ('max_pool_3x3', 1), ('dil_conv_5x5', 2), ('dil_conv_5x5', 1),
               ('dil_conv_5x5', 3), ('sep_conv_5x5', 1), ('sep_conv_5x5', 4)],
              [('dil_conv_5x5', 0), ('skip_connect', 1), ('sep_conv_5x5', 0), ('skip_connect', 1), ('dil_conv_5x5', 2),
               ('sep_conv_5x5', 3), ('sep_conv_5x5', 1), ('sep_conv_5x5', 4)],
              [('dil_conv_5x5', 0), ('skip_connect', 1), ('skip_connect', 1), ('dil_conv_3x3', 2), ('dil_conv_5x5', 0),
               ('sep_conv_5x5', 3), ('dil_conv_3x3', 2), ('dil_conv_5x5', 3)],
              [('skip_connect', 0), ('dil_conv_5x5', 1), ('sep_conv_5x5', 1), ('skip_connect', 2), ('dil_conv_3x3', 1),
               ('dil_conv_5x5', 3), ('dil_conv_5x5', 0), ('dil_conv_5x5', 4)],
              [('skip_connect', 0), ('dil_conv_3x3', 1), ('skip_connect', 1), ('sep_conv_5x5', 2), ('dil_conv_5x5', 0),
               ('dil_conv_5x5', 2), ('dil_conv_5x5', 0), ('dil_conv_3x3', 3)],
              [('sep_conv_5x5', 0), ('max_pool_3x3', 1), ('dil_conv_5x5', 0), ('skip_connect', 2), ('dil_conv_5x5', 0),
               ('sep_conv_3x3', 2), ('sep_conv_5x5', 0), ('dil_conv_3x3', 4)],
              [('sep_conv_5x5', 0), ('skip_connect', 1), ('skip_connect', 0), ('sep_conv_3x3', 2), ('sep_conv_5x5', 1),
               ('dil_conv_3x3', 3), ('sep_conv_5x5', 2), ('dil_conv_5x5', 4)],
              [('sep_conv_3x3', 0), ('skip_connect', 1), ('dil_conv_3x3', 1), ('skip_connect', 2), ('sep_conv_3x3', 2),
               ('sep_conv_3x3', 3), ('dil_conv_5x5', 0), ('dil_conv_3x3', 4)],
              [('skip_connect', 0), ('sep_conv_5x5', 1), ('sep_conv_5x5', 0), ('skip_connect', 1), ('dil_conv_3x3', 0),
               ('sep_conv_3x3', 1), ('sep_conv_5x5', 0), ('dil_conv_3x3', 2)],
              [('sep_conv_5x5', 0), ('skip_connect', 1), ('dil_conv_3x3', 0), ('skip_connect', 1), ('sep_conv_3x3', 1),
               ('sep_conv_5x5', 3), ('dil_conv_3x3', 0), ('dil_conv_5x5', 2)],
              [('sep_conv_5x5', 0), ('skip_connect', 1), ('sep_conv_5x5', 0), ('skip_connect', 2), ('dil_conv_3x3', 0),
               ('dil_conv_5x5', 1), ('dil_conv_5x5', 1), ('dil_conv_3x3', 4)],
              [('skip_connect', 0), ('dil_conv_5x5', 1), ('sep_conv_3x3', 1), ('skip_connect', 2), ('sep_conv_5x5', 0),
               ('dil_conv_3x3', 2), ('dil_conv_5x5', 2), ('dil_conv_5x5', 3)],
              [('sep_conv_5x5', 0), ('skip_connect', 1), ('sep_conv_5x5', 0), ('skip_connect', 2), ('sep_conv_5x5', 0),
               ('sep_conv_3x3', 2), ('dil_conv_5x5', 0), ('sep_conv_3x3', 2)],
              [('dil_conv_3x3', 0), ('skip_connect', 1), ('sep_conv_5x5', 0), ('skip_connect', 1), ('dil_conv_5x5', 1),
               ('sep_conv_5x5', 2), ('dil_conv_5x5', 1), ('sep_conv_5x5', 2)],
              [('dil_conv_5x5', 0), ('skip_connect', 1), ('dil_conv_5x5', 1), ('skip_connect', 2), ('dil_conv_3x3', 2),
               ('dil_conv_3x3', 3), ('sep_conv_3x3', 0), ('sep_conv_3x3', 3)],
              [('sep_conv_3x3', 0), ('skip_connect', 1), ('skip_connect', 0), ('sep_conv_3x3', 2), ('sep_conv_5x5', 0),
               ('dil_conv_5x5', 2), ('dil_conv_3x3', 0), ('sep_conv_3x3', 4)],
              [('sep_conv_5x5', 0), ('skip_connect', 1), ('skip_connect', 0), ('sep_conv_5x5', 1), ('sep_conv_3x3', 2),
               ('sep_conv_3x3', 3), ('dil_conv_5x5', 1), ('sep_conv_3x3', 2)],
              [('dil_conv_5x5', 0), ('skip_connect', 1), ('skip_connect', 0), ('sep_conv_3x3', 2), ('sep_conv_3x3', 0),
               ('sep_conv_5x5', 1), ('dil_conv_3x3', 1), ('sep_conv_5x5', 4)],
              [('skip_connect', 0), ('sep_conv_5x5', 1), ('skip_connect', 0), ('dil_conv_3x3', 1), ('sep_conv_3x3', 0),
               ('sep_conv_5x5', 2), ('sep_conv_5x5', 0), ('dil_conv_5x5', 1)]]

# 最终网络：
# dp=0.25
top_in_10 = [[('dil_conv_5x5', 0), ('sep_conv_5x5', 1), ('sep_conv_3x3', 0), ('sep_conv_5x5', 2), ('sep_conv_3x3', 2),
              ('skip_connect', 3), ('dil_conv_5x5', 3), ('skip_connect', 4)],
             [('sep_conv_3x3', 0), ('skip_connect', 1), ('skip_connect', 1), ('sep_conv_5x5', 2), ('sep_conv_5x5', 2),
              ('dil_conv_5x5', 3), ('dil_conv_5x5', 2), ('dil_conv_5x5', 4)],
             [('dil_conv_5x5', 0), ('skip_connect', 1), ('skip_connect', 1), ('dil_conv_3x3', 2), ('sep_conv_3x3', 1),
              ('sep_conv_5x5', 2), ('sep_conv_5x5', 3), ('sep_conv_5x5', 4)],
             [('sep_conv_5x5', 0), ('skip_connect', 1), ('dil_conv_3x3', 0), ('skip_connect', 1), ('sep_conv_3x3', 1),
              ('sep_conv_3x3', 3), ('sep_conv_3x3', 3), ('dil_conv_5x5', 4)],
             [('sep_conv_3x3', 0), ('skip_connect', 1), ('dil_conv_5x5', 1), ('skip_connect', 2), ('dil_conv_5x5', 0),
              ('sep_conv_3x3', 3), ('dil_conv_5x5', 2), ('dil_conv_3x3', 3)],
             [('skip_connect', 0), ('sep_conv_5x5', 1), ('skip_connect', 0), ('dil_conv_3x3', 1), ('dil_conv_5x5', 1),
              ('sep_conv_3x3', 3), ('sep_conv_5x5', 2), ('sep_conv_5x5', 3)],
             [('skip_connect', 0), ('dil_conv_5x5', 1), ('dil_conv_3x3', 0), ('skip_connect', 2), ('dil_conv_3x3', 1),
              ('sep_conv_3x3', 2), ('dil_conv_3x3', 1), ('dil_conv_5x5', 3)],
             [('skip_connect', 0), ('sep_conv_3x3', 1), ('sep_conv_5x5', 0), ('skip_connect', 1), ('sep_conv_5x5', 1),
              ('sep_conv_5x5', 3), ('dil_conv_5x5', 1), ('dil_conv_3x3', 2)],
             [('sep_conv_5x5', 0), ('skip_connect', 1), ('skip_connect', 0), ('sep_conv_5x5', 2), ('dil_conv_5x5', 2),
              ('dil_conv_5x5', 3), ('dil_conv_5x5', 0), ('sep_conv_5x5', 1)],
             [('sep_conv_5x5', 0), ('skip_connect', 1), ('sep_conv_3x3', 0), ('skip_connect', 2), ('sep_conv_5x5', 0),
              ('dil_conv_3x3', 1), ('dil_conv_5x5', 1), ('sep_conv_3x3', 2)],
             [('skip_connect', 0), ('sep_conv_3x3', 1), ('skip_connect', 0), ('dil_conv_5x5', 2), ('sep_conv_5x5', 1),
              ('dil_conv_5x5', 2), ('sep_conv_3x3', 1), ('dil_conv_5x5', 2)],
             [('dil_conv_3x3', 0), ('skip_connect', 1), ('dil_conv_3x3', 0), ('skip_connect', 2), ('sep_conv_3x3', 1),
              ('sep_conv_5x5', 3), ('dil_conv_5x5', 1), ('dil_conv_5x5', 3)],
             [('skip_connect', 0), ('dil_conv_5x5', 1), ('skip_connect', 0), ('dil_conv_3x3', 1), ('sep_conv_5x5', 1),
              ('sep_conv_3x3', 3), ('sep_conv_5x5', 1), ('dil_conv_3x3', 4)],
             [('sep_conv_5x5', 0), ('skip_connect', 1), ('sep_conv_3x3', 0), ('skip_connect', 2), ('sep_conv_3x3', 0),
              ('sep_conv_5x5', 1), ('dil_conv_3x3', 1), ('dil_conv_5x5', 4)],
             [('skip_connect', 0), ('sep_conv_5x5', 1), ('dil_conv_3x3', 0), ('skip_connect', 1), ('dil_conv_3x3', 1),
              ('sep_conv_5x5', 2), ('dil_conv_5x5', 0), ('dil_conv_5x5', 2)],
             [('skip_connect', 0), ('sep_conv_3x3', 1), ('skip_connect', 0), ('sep_conv_3x3', 1), ('dil_conv_5x5', 0),
              ('sep_conv_3x3', 2), ('sep_conv_5x5', 2), ('sep_conv_5x5', 3)],
             [('skip_connect', 0), ('dil_conv_3x3', 1), ('skip_connect', 1), ('sep_conv_5x5', 2), ('sep_conv_3x3', 0),
              ('dil_conv_3x3', 3), ('sep_conv_5x5', 1), ('dil_conv_3x3', 3)],
             [('skip_connect', 0), ('sep_conv_3x3', 1), ('dil_conv_3x3', 0), ('skip_connect', 2), ('sep_conv_5x5', 2),
              ('sep_conv_3x3', 3), ('sep_conv_5x5', 1), ('sep_conv_5x5', 3)],
             [('skip_connect', 0), ('sep_conv_3x3', 1), ('dil_conv_5x5', 1), ('skip_connect', 2), ('sep_conv_3x3', 1),
              ('sep_conv_3x3', 3), ('dil_conv_5x5', 1), ('sep_conv_5x5', 4)],
             [('skip_connect', 0), ('dil_conv_5x5', 1), ('dil_conv_3x3', 0), ('skip_connect', 2), ('sep_conv_3x3', 1),
              ('sep_conv_3x3', 3), ('sep_conv_5x5', 2), ('sep_conv_3x3', 3)]]

net_iamgenet = [
    [('dil_conv_5x5', 0), ('max_pool_3x3', 1), ('sep_conv_5x5', 1), ('max_pool_3x3', 2), ('sep_conv_5x5', 0),
     ('sep_conv_3x3', 3), ('dil_conv_5x5', 0), ('sep_conv_5x5', 2)],
    [('dil_conv_3x3', 0), ('max_pool_3x3', 1), ('dil_conv_5x5', 0), ('max_pool_3x3', 1), ('dil_conv_5x5', 2),
     ('dil_conv_5x5', 3), ('dil_conv_5x5', 1), ('dil_conv_3x3', 3)],
    [('sep_conv_5x5', 0), ('max_pool_3x3', 1), ('dil_conv_5x5', 0), ('max_pool_3x3', 2), ('dil_conv_5x5', 0),
     ('dil_conv_5x5', 2), ('dil_conv_3x3', 0), ('sep_conv_3x3', 1)],
    [('max_pool_3x3', 0), ('sep_conv_5x5', 1), ('max_pool_3x3', 0), ('sep_conv_3x3', 1), ('dil_conv_3x3', 0),
     ('sep_conv_5x5', 2), ('dil_conv_3x3', 0), ('dil_conv_5x5', 4)],
    [('sep_conv_5x5', 0), ('max_pool_3x3', 1), ('dil_conv_5x5', 0), ('max_pool_3x3', 2), ('sep_conv_5x5', 0),
     ('dil_conv_5x5', 1), ('dil_conv_5x5', 0), ('sep_conv_5x5', 4)],
    [('sep_conv_5x5', 0), ('max_pool_3x3', 1), ('max_pool_3x3', 0), ('sep_conv_5x5', 2), ('dil_conv_5x5', 0),
     ('dil_conv_5x5', 2), ('sep_conv_5x5', 0), ('dil_conv_5x5', 1)],
    [('dil_conv_5x5', 0), ('max_pool_3x3', 1), ('max_pool_3x3', 0), ('sep_conv_5x5', 1), ('dil_conv_5x5', 0),
     ('dil_conv_3x3', 2), ('dil_conv_5x5', 1), ('dil_conv_5x5', 4)],
    [('max_pool_3x3', 0), ('dil_conv_3x3', 1), ('max_pool_3x3', 0), ('dil_conv_5x5', 1), ('dil_conv_3x3', 0),
     ('sep_conv_5x5', 1), ('sep_conv_5x5', 0), ('dil_conv_5x5', 4)],
    [('max_pool_3x3', 0), ('sep_conv_5x5', 1), ('dil_conv_5x5', 0), ('max_pool_3x3', 1), ('sep_conv_5x5', 0),
     ('dil_conv_5x5', 1), ('dil_conv_5x5', 0), ('sep_conv_5x5', 1)],
    [('max_pool_3x3', 0), ('dil_conv_3x3', 1), ('sep_conv_5x5', 1), ('skip_connect', 2), ('dil_conv_5x5', 0),
     ('sep_conv_5x5', 1), ('dil_conv_5x5', 1), ('sep_conv_5x5', 4)],
    [('skip_connect', 0), ('dil_conv_3x3', 1), ('dil_conv_5x5', 1), ('skip_connect', 2), ('sep_conv_5x5', 0),
     ('dil_conv_5x5', 3), ('sep_conv_5x5', 0), ('sep_conv_5x5', 1)],
    [('sep_conv_5x5', 0), ('skip_connect', 1), ('sep_conv_5x5', 0), ('skip_connect', 2), ('sep_conv_5x5', 1),
     ('dil_conv_5x5', 2), ('dil_conv_3x3', 0), ('sep_conv_5x5', 4)],
    [('dil_conv_3x3', 0), ('skip_connect', 1), ('skip_connect', 0), ('dil_conv_5x5', 2), ('dil_conv_3x3', 0),
     ('sep_conv_5x5', 2), ('sep_conv_3x3', 1), ('sep_conv_5x5', 3)],
    [('dil_conv_3x3', 0), ('skip_connect', 1), ('skip_connect', 1), ('sep_conv_5x5', 2), ('dil_conv_5x5', 0),
     ('dil_conv_3x3', 1), ('sep_conv_5x5', 1), ('sep_conv_5x5', 2)]]

# dp=0.30
top_in_100 = model_score_77

net_meco = [[('sep_conv_5x5', 0), ('sep_conv_5x5', 1), ('sep_conv_5x5', 1), ('sep_conv_5x5', 2), ('sep_conv_5x5', 1),
             ('sep_conv_5x5', 3), ('sep_conv_5x5', 2), ('sep_conv_3x3', 4)],
            [('sep_conv_5x5', 0), ('sep_conv_5x5', 1), ('sep_conv_5x5', 1), ('sep_conv_3x3', 2), ('sep_conv_3x3', 1),
             ('sep_conv_5x5', 2), ('sep_conv_5x5', 1), ('sep_conv_5x5', 4)],
            [('sep_conv_5x5', 0), ('sep_conv_5x5', 1), ('sep_conv_3x3', 0), ('sep_conv_5x5', 1), ('sep_conv_3x3', 1),
             ('sep_conv_3x3', 3), ('sep_conv_3x3', 1), ('sep_conv_5x5', 2)],
            [('sep_conv_5x5', 0), ('sep_conv_5x5', 1), ('sep_conv_5x5', 0), ('sep_conv_5x5', 2), ('sep_conv_5x5', 1),
             ('sep_conv_5x5', 3), ('sep_conv_5x5', 0), ('sep_conv_5x5', 2)],
            [('sep_conv_5x5', 0), ('sep_conv_5x5', 1), ('sep_conv_3x3', 0), ('sep_conv_5x5', 1), ('sep_conv_3x3', 0),
             ('sep_conv_5x5', 2), ('sep_conv_3x3', 0), ('sep_conv_5x5', 1)],
            [('sep_conv_5x5', 0), ('sep_conv_5x5', 1), ('sep_conv_5x5', 0), ('sep_conv_5x5', 1), ('sep_conv_5x5', 0),
             ('sep_conv_5x5', 2), ('sep_conv_5x5', 1), ('sep_conv_5x5', 2)],
            [('sep_conv_5x5', 0), ('sep_conv_5x5', 1), ('sep_conv_5x5', 0), ('sep_conv_5x5', 1), ('sep_conv_3x3', 1),
             ('sep_conv_5x5', 2), ('sep_conv_5x5', 2), ('sep_conv_5x5', 3)],
            [('sep_conv_5x5', 0), ('sep_conv_3x3', 1), ('sep_conv_3x3', 1), ('sep_conv_3x3', 2), ('sep_conv_3x3', 0),
             ('sep_conv_5x5', 1), ('sep_conv_5x5', 0), ('sep_conv_5x5', 4)],
            [('sep_conv_3x3', 0), ('sep_conv_3x3', 1), ('sep_conv_5x5', 1), ('sep_conv_5x5', 2), ('sep_conv_5x5', 0),
             ('sep_conv_3x3', 3), ('sep_conv_5x5', 0), ('sep_conv_5x5', 2)],
            [('sep_conv_3x3', 0), ('sep_conv_5x5', 1), ('sep_conv_3x3', 0), ('sep_conv_5x5', 1), ('sep_conv_5x5', 0),
             ('sep_conv_5x5', 1), ('sep_conv_3x3', 2), ('sep_conv_5x5', 4)],
            [('sep_conv_3x3', 0), ('sep_conv_3x3', 1), ('sep_conv_5x5', 0), ('sep_conv_3x3', 1), ('sep_conv_5x5', 0),
             ('sep_conv_5x5', 1), ('sep_conv_5x5', 0), ('sep_conv_3x3', 3)],
            [('sep_conv_5x5', 0), ('sep_conv_3x3', 1), ('sep_conv_5x5', 0), ('sep_conv_3x3', 1), ('sep_conv_5x5', 0),
             ('sep_conv_3x3', 1), ('sep_conv_5x5', 0), ('sep_conv_5x5', 4)],
            [('sep_conv_5x5', 0), ('sep_conv_3x3', 1), ('sep_conv_3x3', 1), ('sep_conv_3x3', 2), ('sep_conv_3x3', 1),
             ('sep_conv_5x5', 2), ('sep_conv_3x3', 0), ('sep_conv_5x5', 1)],
            [('sep_conv_3x3', 0), ('sep_conv_5x5', 1), ('sep_conv_3x3', 0), ('sep_conv_3x3', 1), ('sep_conv_3x3', 0),
             ('sep_conv_3x3', 3), ('sep_conv_3x3', 1), ('sep_conv_3x3', 3)],
            [('sep_conv_5x5', 0), ('sep_conv_3x3', 1), ('sep_conv_3x3', 1), ('sep_conv_3x3', 2), ('sep_conv_3x3', 1),
             ('sep_conv_5x5', 2), ('sep_conv_3x3', 0), ('sep_conv_3x3', 2)],
            [('sep_conv_3x3', 0), ('sep_conv_3x3', 1), ('sep_conv_5x5', 0), ('sep_conv_3x3', 2), ('sep_conv_5x5', 0),
             ('sep_conv_5x5', 1), ('sep_conv_3x3', 1), ('sep_conv_3x3', 3)],
            [('sep_conv_5x5', 0), ('sep_conv_3x3', 1), ('sep_conv_3x3', 0), ('sep_conv_3x3', 1), ('sep_conv_5x5', 0),
             ('sep_conv_5x5', 1), ('sep_conv_3x3', 0), ('sep_conv_5x5', 4)],
            [('sep_conv_3x3', 0), ('sep_conv_5x5', 1), ('sep_conv_5x5', 0), ('sep_conv_5x5', 1), ('sep_conv_5x5', 0),
             ('sep_conv_5x5', 1), ('sep_conv_3x3', 1), ('sep_conv_5x5', 2)],
            [('sep_conv_5x5', 0), ('sep_conv_3x3', 1), ('sep_conv_3x3', 0), ('sep_conv_3x3', 1), ('sep_conv_3x3', 0),
             ('sep_conv_3x3', 3), ('sep_conv_5x5', 1), ('sep_conv_5x5', 4)],
            [('sep_conv_3x3', 0), ('sep_conv_3x3', 1), ('sep_conv_5x5', 0), ('sep_conv_3x3', 2), ('sep_conv_5x5', 1),
             ('sep_conv_3x3', 2), ('sep_conv_5x5', 1), ('sep_conv_5x5', 4)]]

net_cifar100 = [
    [('max_pool_3x3', 0), ('max_pool_3x3', 1), ('max_pool_3x3', 1), ('skip_connect', 2), ('max_pool_3x3', 0),
     ('skip_connect', 3), ('max_pool_3x3', 0), ('max_pool_3x3', 1)], [('skip_connect',
                                                                       0), ('sep_conv_3x3', 1), ('max_pool_3x3', 0),
                                                                      ('max_pool_3x3', 2), ('max_pool_3x3', 0),
                                                                      ('skip_connect', 3), ('max_pool_3x3', 0),
                                                                      ('max_pool_3x3', 3)],
    [('skip_connect', 0), ('dil_conv_5x5', 1), ('skip_connect', 1), ('max_pool_3x3', 2), ('max_pool_3x3', 2),
     ('max_pool_3x3', 3), ('skip_connect', 2), ('max_pool_3x3', 3)],
    [('max_pool_3x3', 0), ('max_pool_3x3', 1), ('sep_conv_3x3', 1), ('skip_connect', 2), ('skip_connect', 2),
     ('max_pool_3x3', 3), ('skip_connect', 3), ('avg_pool_3x3', 4)],
    [('sep_conv_3x3', 0), ('dil_conv_3x3', 1), ('max_pool_3x3', 0), ('dil_conv_3x3', 2), ('skip_connect', 2),
     ('skip_connect', 3), ('dil_conv_5x5', 2), ('skip_connect', 4)],
    [('sep_conv_5x5', 0), ('max_pool_3x3', 1), ('sep_conv_3x3', 1), ('skip_connect', 2), ('sep_conv_5x5', 2),
     ('skip_connect', 3), ('skip_connect', 2), ('skip_connect', 4)],
    [('sep_conv_5x5', 0), ('dil_conv_5x5', 1), ('skip_connect', 1), ('skip_connect', 2), ('sep_conv_5x5', 2),
     ('skip_connect', 3), ('skip_connect', 3), ('skip_connect', 4)],
    [('sep_conv_5x5', 0), ('skip_connect', 1), ('sep_conv_5x5', 1), ('skip_connect', 2), ('dil_conv_3x3', 1),
     ('skip_connect', 3), ('sep_conv_3x3', 1), ('skip_connect', 3)],
    [('sep_conv_3x3', 0), ('skip_connect', 1), ('sep_conv_5x5', 1), ('dil_conv_3x3', 2), ('sep_conv_5x5', 1),
     ('sep_conv_3x3', 2), ('skip_connect', 3), ('skip_connect', 4)],
    [('dil_conv_3x3', 0), ('skip_connect', 1), ('sep_conv_5x5', 1), ('skip_connect', 2), ('skip_connect', 1),
     ('skip_connect', 2), ('skip_connect', 3), ('skip_connect', 4)],
    [('skip_connect', 0), ('sep_conv_3x3', 1), ('skip_connect', 0), ('skip_connect', 2), ('skip_connect', 2),
     ('skip_connect', 3), ('skip_connect', 2), ('skip_connect', 3)],
    [('sep_conv_5x5', 0), ('sep_conv_5x5', 1), ('max_pool_3x3', 1), ('skip_connect', 2), ('sep_conv_5x5', 1),
     ('skip_connect', 3), ('skip_connect', 3), ('skip_connect', 4)],
    [('sep_conv_5x5', 0), ('skip_connect', 1), ('sep_conv_5x5', 1), ('skip_connect', 2), ('skip_connect', 1),
     ('dil_conv_3x3', 2), ('skip_connect', 3), ('skip_connect', 4)],
    [('dil_conv_3x3', 0), ('sep_conv_3x3', 1), ('sep_conv_5x5', 0), ('dil_conv_3x3', 2), ('sep_conv_5x5', 0),
     ('sep_conv_5x5', 2), ('dil_conv_3x3', 2), ('skip_connect', 4)],
    [('skip_connect', 0), ('skip_connect', 1), ('dil_conv_3x3', 0), ('dil_conv_5x5', 2), ('skip_connect', 1),
     ('dil_conv_3x3', 2), ('dil_conv_5x5', 1), ('dil_conv_5x5', 2)],
    [('sep_conv_3x3', 0), ('skip_connect', 1), ('skip_connect', 0), ('skip_connect', 2), ('sep_conv_3x3', 0),
     ('skip_connect', 2), ('dil_conv_5x5', 0), ('sep_conv_3x3', 3)],
    [('dil_conv_3x3', 0), ('sep_conv_5x5', 1), ('sep_conv_5x5', 1), ('dil_conv_3x3', 2), ('skip_connect', 0),
     ('dil_conv_5x5', 1), ('dil_conv_5x5', 3), ('sep_conv_3x3', 4)],
    [('skip_connect', 0), ('skip_connect', 1), ('sep_conv_3x3', 1), ('skip_connect', 2), ('sep_conv_5x5', 1),
     ('skip_connect', 3), ('skip_connect', 0), ('sep_conv_3x3', 4)],
    [('sep_conv_3x3', 0), ('skip_connect', 1), ('sep_conv_3x3', 1), ('dil_conv_3x3', 2), ('sep_conv_5x5', 0),
     ('skip_connect', 1), ('skip_connect', 0), ('dil_conv_3x3', 1)],
    [('sep_conv_3x3', 0), ('skip_connect', 1), ('sep_conv_3x3', 0), ('skip_connect', 2), ('sep_conv_5x5', 0),
     ('sep_conv_5x5', 2), ('sep_conv_3x3', 1), ('sep_conv_5x5', 4)]]

s1_model1 = [[('dil_conv_3x3', 0), ('skip_connect', 1), ('skip_connect', 1), ('skip_connect', 2), ('dil_conv_5x5', 0), ('dil_conv_5x5', 2), ('skip_connect', 2), ('skip_connect', 3)], [('skip_connect', 0), ('dil_conv_3x3', 1), ('skip_connect', 1), ('skip_connect', 2), ('skip_connect', 2), ('skip_connect', 3), ('skip_connect', 2), ('skip_connect', 3)], [('dil_conv_3x3', 0), ('dil_conv_3x3', 1), ('skip_connect', 0), ('skip_connect', 2), ('skip_connect', 2), ('skip_connect', 3), ('skip_connect', 3), ('skip_connect', 4)], [('skip_connect', 0), ('dil_conv_3x3', 1), ('dil_conv_5x5', 0), ('skip_connect', 2), ('dil_conv_5x5', 0), ('skip_connect', 3), ('sep_conv_3x3', 2), ('skip_connect', 4)], [('dil_conv_3x3', 0), ('skip_connect', 1), ('dil_conv_5x5', 0), ('skip_connect', 2), ('skip_connect', 2), ('skip_connect', 3), ('skip_connect', 2), ('skip_connect', 4)], [('skip_connect', 0), ('skip_connect', 1), ('skip_connect', 0), ('skip_connect', 2), ('skip_connect', 2), ('skip_connect', 3), ('skip_connect', 3), ('skip_connect', 4)], [('max_pool_3x3', 0), ('max_pool_3x3', 1), ('max_pool_3x3', 0), ('max_pool_3x3', 1), ('max_pool_3x3', 0), ('max_pool_3x3', 1), ('max_pool_3x3', 0), ('max_pool_3x3', 1)], [('skip_connect', 0), ('skip_connect', 1), ('dil_conv_5x5', 0), ('skip_connect', 2), ('skip_connect', 2), ('skip_connect', 3), ('sep_conv_3x3', 0), ('sep_conv_3x3', 2)], [('dil_conv_3x3', 0), ('skip_connect', 1), ('dil_conv_5x5', 0), ('skip_connect', 2), ('skip_connect',
2), ('skip_connect', 3), ('skip_connect', 3), ('skip_connect', 4)], [('dil_conv_3x3', 0), ('skip_connect', 1), ('dil_conv_5x5', 1), ('skip_connect', 2), ('skip_connect', 0), ('skip_connect', 3), ('skip_connect', 3), ('skip_connect', 4)], [('dil_conv_3x3', 0), ('skip_connect', 1), ('skip_connect', 0), ('skip_connect', 2), ('skip_connect', 1), ('skip_connect', 3), ('skip_connect', 1), ('sep_conv_3x3', 3)], [('skip_connect', 0), ('dil_conv_3x3', 1), ('skip_connect', 1), ('skip_connect', 2), ('skip_connect', 0), ('skip_connect', 3), ('skip_connect', 2), ('skip_connect', 3)], [('skip_connect', 0), ('skip_connect', 1), ('skip_connect', 0), ('dil_conv_5x5', 1), ('skip_connect', 2), ('skip_connect', 3), ('sep_conv_3x3', 3), ('skip_connect', 4)], [('max_pool_3x3', 0), ('max_pool_3x3', 1), ('dil_conv_3x3', 0), ('dil_conv_3x3', 1), ('avg_pool_3x3', 0), ('max_pool_3x3', 1), ('max_pool_3x3', 0), ('max_pool_3x3', 1)], [('skip_connect', 0), ('dil_conv_3x3', 1), ('dil_conv_5x5', 1), ('dil_conv_5x5', 2), ('dil_conv_5x5', 0), ('skip_connect', 3),
('sep_conv_3x3', 3), ('sep_conv_3x3', 4)], [('dil_conv_3x3', 0), ('skip_connect', 1), ('skip_connect', 1), ('skip_connect', 2), ('skip_connect', 2), ('skip_connect', 3), ('skip_connect', 3), ('skip_connect', 4)], [('skip_connect', 0), ('skip_connect', 1), ('skip_connect', 0), ('skip_connect', 2), ('skip_connect', 2), ('skip_connect', 3), ('skip_connect', 3), ('sep_conv_3x3', 4)], [('dil_conv_3x3', 0), ('skip_connect', 1), ('skip_connect', 0), ('skip_connect', 1), ('dil_conv_5x5', 1), ('skip_connect', 2), ('skip_connect', 0), ('sep_conv_3x3', 3)], [('dil_conv_3x3', 0), ('skip_connect', 1), ('skip_connect', 0), ('dil_conv_5x5', 2), ('skip_connect', 0), ('dil_conv_5x5', 3), ('skip_connect', 0), ('skip_connect', 1)], [('skip_connect', 0), ('skip_connect', 1), ('dil_conv_5x5', 1), ('skip_connect', 2), ('dil_conv_5x5', 0), ('skip_connect', 3), ('sep_conv_3x3', 2), ('skip_connect', 3)]]

s2_model1 = [[('skip_connect', 0), ('skip_connect', 1), ('sep_conv_3x3', 0), ('skip_connect', 1), ('sep_conv_3x3', 1), ('skip_connect', 3), ('skip_connect', 3), ('skip_connect', 4)], [('skip_connect', 0), ('skip_connect', 1), ('skip_connect', 1), ('skip_connect', 2), ('sep_conv_3x3', 1), ('skip_connect', 2), ('skip_connect', 0), ('skip_connect', 4)], [('skip_connect', 0), ('skip_connect', 1), ('skip_connect', 0), ('sep_conv_3x3', 1), ('skip_connect', 2), ('skip_connect', 3), ('skip_connect', 3), ('skip_connect', 4)], [('skip_connect', 0), ('sep_conv_3x3', 1), ('skip_connect', 0), ('skip_connect', 2), ('skip_connect', 2), ('skip_connect', 3), ('skip_connect', 0), ('skip_connect', 3)], [('skip_connect', 0), ('skip_connect', 1), ('skip_connect', 1), ('skip_connect', 2), ('skip_connect', 2), ('skip_connect', 3), ('skip_connect', 2), ('skip_connect', 4)], [('skip_connect', 0), ('sep_conv_3x3', 1), ('skip_connect', 1), ('skip_connect', 2), ('sep_conv_3x3', 0), ('skip_connect', 3), ('skip_connect', 0), ('skip_connect', 4)], [('sep_conv_3x3', 0), ('skip_connect', 1), ('sep_conv_3x3', 1), ('sep_conv_3x3', 2), ('skip_connect', 1), ('skip_connect', 2), ('skip_connect', 2), ('skip_connect', 3)], [('skip_connect', 0), ('skip_connect', 1), ('skip_connect', 1), ('skip_connect', 2), ('skip_connect', 2), ('skip_connect', 3), ('skip_connect', 1), ('skip_connect', 2)], [('sep_conv_3x3', 0), ('skip_connect', 1), ('sep_conv_3x3', 0), ('skip_connect', 2), ('skip_connect', 2), ('skip_connect', 3), ('skip_connect', 3), ('skip_connect', 4)], [('sep_conv_3x3', 0), ('sep_conv_3x3', 1), ('skip_connect', 0), ('skip_connect', 2), ('skip_connect', 2), ('skip_connect', 3), ('skip_connect', 3), ('skip_connect', 4)], [('skip_connect', 0), ('sep_conv_3x3', 1), ('skip_connect', 1), ('skip_connect', 2), ('sep_conv_3x3', 2), ('skip_connect', 3), ('sep_conv_3x3', 2), ('skip_connect', 4)], [('skip_connect', 0), ('skip_connect', 1), ('sep_conv_3x3', 1), ('sep_conv_3x3', 2), ('skip_connect', 0), ('skip_connect', 2), ('skip_connect', 1), ('skip_connect', 3)], [('skip_connect', 0), ('sep_conv_3x3', 1), ('skip_connect', 1), ('skip_connect', 2), ('skip_connect', 2), ('skip_connect', 3), ('skip_connect', 2), ('skip_connect', 4)], [('sep_conv_3x3', 0), ('skip_connect', 1), ('skip_connect', 1), ('skip_connect', 2), ('sep_conv_3x3', 1), ('skip_connect', 2), ('sep_conv_3x3', 1), ('skip_connect', 3)], [('skip_connect', 0), ('sep_conv_3x3', 1), ('sep_conv_3x3', 1), ('skip_connect', 2), ('sep_conv_3x3', 1), ('skip_connect', 2), ('skip_connect', 3), ('skip_connect', 4)], [('skip_connect', 0), ('skip_connect', 1), ('sep_conv_3x3', 0), ('skip_connect', 1), ('sep_conv_3x3', 0), ('skip_connect', 2), ('skip_connect', 0), ('skip_connect', 2)], [('sep_conv_3x3', 0), ('sep_conv_3x3', 1), ('skip_connect', 0), ('sep_conv_3x3', 1), ('skip_connect', 0), ('skip_connect', 2), ('skip_connect', 1), ('skip_connect', 3)], [('skip_connect', 0), ('skip_connect', 1), ('sep_conv_3x3', 0), ('skip_connect', 2), ('skip_connect', 0), ('skip_connect', 2), ('skip_connect', 1), ('skip_connect', 2)], [('sep_conv_3x3', 0), ('skip_connect', 1), ('sep_conv_3x3', 1), ('skip_connect', 2), ('skip_connect', 0), ('skip_connect', 1), ('sep_conv_3x3', 2), ('skip_connect', 4)], [('skip_connect', 0), ('skip_connect', 1), ('skip_connect', 0), ('skip_connect', 2), ('sep_conv_3x3', 0), ('skip_connect', 1), ('skip_connect', 3), ('skip_connect', 4)]]

s3_model1 = [[('skip_connect', 0), ('skip_connect', 1), ('skip_connect', 0), ('skip_connect', 1), ('skip_connect', 0), ('skip_connect', 2), ('skip_connect', 1), ('skip_connect', 4)], [('skip_connect', 0), ('sep_conv_3x3', 1), ('skip_connect', 0), ('skip_connect', 2), ('skip_connect', 0), ('skip_connect', 3), ('skip_connect', 2), ('skip_connect', 3)], [('skip_connect', 0), ('sep_conv_3x3', 1), ('sep_conv_3x3', 1), ('skip_connect', 2), ('sep_conv_3x3', 2), ('skip_connect', 3), ('skip_connect', 3), ('skip_connect', 4)], [('skip_connect', 0), ('skip_connect', 1), ('skip_connect', 1), ('skip_connect', 2), ('skip_connect', 2), ('skip_connect', 3), ('skip_connect', 3), ('skip_connect', 4)], [('skip_connect', 0), ('skip_connect', 1), ('skip_connect', 0), ('skip_connect', 1), ('skip_connect', 2), ('sep_conv_3x3', 3), ('skip_connect', 2), ('skip_connect', 4)], [('sep_conv_3x3', 0), ('skip_connect', 1), ('sep_conv_3x3', 0), ('skip_connect', 2), ('skip_connect', 2), ('skip_connect', 3), ('sep_conv_3x3', 2), ('skip_connect', 4)], [('sep_conv_3x3', 0), ('sep_conv_3x3', 1), ('skip_connect', 1), ('skip_connect', 2), ('skip_connect', 2), ('skip_connect', 3), ('skip_connect', 2), ('sep_conv_3x3', 4)], [('skip_connect', 0), ('sep_conv_3x3', 1), ('sep_conv_3x3', 0), ('skip_connect', 2), ('skip_connect', 0), ('skip_connect', 3), ('skip_connect', 2), ('skip_connect', 3)], [('skip_connect', 0), ('sep_conv_3x3', 1), ('skip_connect', 1), ('skip_connect', 2), ('sep_conv_3x3', 1), ('skip_connect', 2), ('skip_connect', 3), ('sep_conv_3x3', 4)], [('sep_conv_3x3', 0), ('sep_conv_3x3', 1), ('skip_connect', 1), ('skip_connect', 2), ('skip_connect', 2), ('skip_connect', 3), ('skip_connect', 3), ('skip_connect', 4)], [('skip_connect', 0), ('sep_conv_3x3', 1), ('skip_connect', 0), ('sep_conv_3x3', 1), ('skip_connect', 2), ('skip_connect', 3), ('skip_connect', 2), ('skip_connect', 4)], [('skip_connect', 0), ('skip_connect', 1), ('skip_connect', 1), ('skip_connect', 2), ('skip_connect', 2), ('skip_connect', 3), ('skip_connect', 2), ('skip_connect', 4)], [('sep_conv_3x3', 0), ('skip_connect', 1), ('sep_conv_3x3', 1), ('skip_connect', 2), ('skip_connect', 2), ('skip_connect', 3), ('skip_connect', 2), ('skip_connect', 4)], [('sep_conv_3x3', 0), ('sep_conv_3x3', 1), ('sep_conv_3x3', 0), ('skip_connect', 1), ('skip_connect', 0), ('skip_connect', 1), ('skip_connect', 2), ('skip_connect', 4)], [('skip_connect', 0), ('skip_connect', 1), ('sep_conv_3x3', 0), ('sep_conv_3x3', 1), ('sep_conv_3x3', 2), ('sep_conv_3x3', 3), ('skip_connect', 1), ('skip_connect', 2)], [('sep_conv_3x3', 0), ('sep_conv_3x3', 1), ('sep_conv_3x3', 0), ('skip_connect', 2), ('skip_connect', 1), ('sep_conv_3x3', 3), ('skip_connect', 1), ('sep_conv_3x3', 4)], [('skip_connect', 0), ('skip_connect', 1), ('skip_connect', 0), ('skip_connect', 1), ('sep_conv_3x3', 0), ('skip_connect', 2), ('skip_connect', 2), ('skip_connect', 3)], [('skip_connect', 0), ('skip_connect', 1), ('sep_conv_3x3', 0), ('sep_conv_3x3', 2), ('sep_conv_3x3', 1), ('skip_connect', 2), ('skip_connect', 0), ('skip_connect', 4)], [('skip_connect', 0), ('skip_connect', 1), ('skip_connect', 1), ('skip_connect', 2), ('skip_connect', 2), ('sep_conv_3x3', 3), ('skip_connect', 2), ('skip_connect', 3)], [('skip_connect', 0), ('skip_connect', 1), ('skip_connect', 0), ('skip_connect', 2), ('skip_connect', 2), ('skip_connect', 3), ('skip_connect', 2), ('skip_connect', 4)]]

s4_model1 = [[('noise', 0), ('noise', 1), ('noise', 0), ('noise', 1), ('noise', 1), ('noise', 3), ('noise', 0), ('noise', 1)], [('noise', 0), ('noise', 1), ('noise', 1), ('noise', 2), ('noise', 0), ('noise', 2), ('noise', 3), ('noise', 4)], [('noise', 0), ('noise', 1), ('noise', 0), ('noise', 1), ('noise', 2), ('noise', 3), ('noise', 0), ('noise', 2)], [('noise', 0), ('noise', 1), ('noise', 0), ('noise', 2), ('noise', 0), ('noise', 2), ('noise', 0), ('noise', 3)], [('noise', 0), ('noise', 1), ('noise', 0), ('noise', 2), ('noise', 2), ('noise', 3), ('noise', 0), ('noise', 4)], [('noise', 0), ('noise', 1), ('noise', 1), ('noise', 2), ('noise', 1), ('noise', 2), ('noise', 0), ('noise', 1)], [('noise', 0), ('noise', 1), ('noise', 1), ('noise', 2), ('noise', 2), ('noise', 3), ('noise', 0), ('noise', 1)], [('noise', 0), ('noise', 1), ('noise', 0), ('noise', 1), ('noise', 2), ('noise', 3), ('noise', 1), ('noise', 4)], [('noise', 0), ('noise', 1), ('noise', 1), ('noise', 2), ('noise', 0), ('noise', 2), ('noise', 3), ('noise', 4)], [('noise', 0), ('noise', 1), ('noise', 0), ('noise', 2), ('noise', 1), ('noise', 3), ('noise', 0), ('noise', 4)], [('noise', 0), ('noise', 1), ('noise', 0), ('noise', 1), ('noise', 0), ('noise', 3), ('noise', 0), ('noise', 4)], [('noise', 0), ('noise', 1), ('noise', 1), ('noise', 2), ('noise', 1), ('noise', 2), ('noise', 1), ('noise', 4)], [('noise', 0), ('noise', 1), ('noise', 1), ('noise', 2), ('noise', 1), ('noise', 2), ('noise', 0), ('noise', 1)], [('noise', 0), ('noise', 1), ('noise', 1), ('noise', 2), ('noise', 0), ('noise', 1), ('noise', 1), ('noise', 4)], [('noise', 0), ('noise', 1), ('noise', 0), ('noise', 2), ('noise', 0), ('noise', 3), ('noise', 0), ('noise', 3)], [('noise', 0), ('noise', 1), ('noise', 0), ('sep_conv_3x3', 2), ('noise', 0), ('noise', 1), ('noise', 1), ('sep_conv_3x3', 4)], [('noise', 0), ('noise', 1), ('noise', 0), ('noise', 1), ('sep_conv_3x3', 2), ('noise', 3), ('noise', 1), ('noise', 2)], [('noise', 0), ('noise', 1), ('noise', 0), ('noise', 1), ('noise', 0), ('noise', 3), ('noise', 1), ('noise', 3)], [('noise', 0), ('noise', 1), ('sep_conv_3x3', 0), ('sep_conv_3x3', 2), ('noise', 1), ('noise', 2), ('noise', 2), ('noise', 4)], [('noise', 0), ('noise', 1), ('noise', 1), ('noise', 2), ('sep_conv_3x3', 1), ('noise', 3), ('noise', 1), ('noise', 4)]]

s5_model1 = [[('max_pool_3x3', 0), ('sep_conv_3x3', 1), ('max_pool_3x3', 0), ('sep_conv_5x5', 1), ('max_pool_3x3', 0), ('dil_conv_3x3', 1), ('max_pool_3x3', 0), ('sep_conv_3x3', 3)], [('max_pool_3x3', 0), ('dil_conv_5x5', 1), ('max_pool_3x3', 0), ('sep_conv_3x3', 2), ('sep_conv_5x5', 0), ('skip_connect', 1), ('sep_conv_5x5', 1), ('skip_connect', 4)], [('skip_connect', 0), ('dil_conv_3x3', 1), ('skip_connect', 0), ('dil_conv_5x5', 1), ('sep_conv_5x5', 0), ('max_pool_3x3', 2), ('dil_conv_5x5', 2), ('skip_connect', 4)], [('max_pool_3x3', 0), ('sep_conv_3x3', 1), ('skip_connect', 0), ('dil_conv_3x3', 2), ('dil_conv_3x3', 2), ('skip_connect', 3), ('dil_conv_5x5', 0), ('skip_connect', 2)], [('max_pool_3x3', 0), ('dil_conv_5x5', 1), ('max_pool_3x3', 0), ('dil_conv_3x3', 1), ('max_pool_3x3', 0), ('dil_conv_5x5', 1), ('dil_conv_5x5', 0), ('skip_connect', 1)], [('dil_conv_5x5', 0), ('skip_connect', 1), ('max_pool_3x3', 1), ('sep_conv_5x5', 2), ('sep_conv_3x3', 0), ('skip_connect', 3), ('dil_conv_3x3', 1), ('skip_connect', 2)], [('skip_connect', 0), ('dil_conv_3x3', 1), ('dil_conv_3x3', 0), ('skip_connect', 2), ('sep_conv_3x3', 1), ('skip_connect', 2), ('dil_conv_5x5', 2), ('skip_connect', 4)], [('dil_conv_5x5', 0), ('sep_conv_3x3', 1), ('skip_connect', 0), ('dil_conv_5x5', 1), ('dil_conv_3x3', 0), ('skip_connect', 2), ('skip_connect', 2), ('dil_conv_5x5', 4)], [('dil_conv_3x3', 0), ('skip_connect', 1), ('sep_conv_5x5', 0), ('skip_connect', 1), ('sep_conv_5x5', 0), ('skip_connect', 2), ('skip_connect', 3), ('dil_conv_5x5', 4)], [('dil_conv_3x3', 0), ('skip_connect', 1), ('dil_conv_3x3', 0), ('sep_conv_3x3', 1), ('skip_connect', 1), ('sep_conv_3x3', 3), ('skip_connect', 0), ('dil_conv_3x3', 1)], [('skip_connect', 0), ('dil_conv_5x5', 1), ('dil_conv_5x5', 0), ('skip_connect', 1), ('sep_conv_3x3', 0), ('skip_connect', 2), ('skip_connect', 0), ('dil_conv_3x3', 4)], [('sep_conv_5x5', 0), ('skip_connect', 1), ('skip_connect', 1), ('dil_conv_3x3', 2), ('dil_conv_3x3', 1), ('skip_connect', 3), ('dil_conv_5x5', 1), ('skip_connect', 4)], [('dil_conv_3x3', 0), ('skip_connect', 1), ('skip_connect', 0), ('dil_conv_3x3', 1), ('skip_connect', 0), ('sep_conv_5x5', 1), ('sep_conv_5x5', 0), ('skip_connect', 2)], [('dil_conv_3x3', 0), ('dil_conv_3x3', 1), ('skip_connect', 0), ('sep_conv_5x5', 2), ('dil_conv_5x5', 0), ('skip_connect', 3), ('sep_conv_3x3', 2), ('dil_conv_3x3', 4)], [('dil_conv_3x3', 0), ('skip_connect', 1), ('dil_conv_5x5', 0), ('skip_connect', 2), ('skip_connect', 1), ('sep_conv_5x5', 3), ('dil_conv_3x3', 0), ('sep_conv_5x5', 4)], [('sep_conv_5x5', 0), ('skip_connect', 1), ('sep_conv_3x3', 0), ('skip_connect', 1), ('skip_connect', 0), ('sep_conv_5x5', 1), ('skip_connect', 0), ('dil_conv_5x5', 2)], [('sep_conv_3x3', 0), ('sep_conv_5x5', 1), ('skip_connect', 0), ('dil_conv_3x3', 1), ('skip_connect', 1), ('dil_conv_3x3', 2), ('dil_conv_3x3', 0), ('sep_conv_3x3', 1)], [('skip_connect', 0), ('dil_conv_3x3', 1), ('dil_conv_3x3', 0), ('skip_connect', 2), ('skip_connect', 0), ('dil_conv_5x5', 1), ('sep_conv_3x3', 2), ('sep_conv_3x3', 4)], [('sep_conv_5x5', 0), ('skip_connect', 1), ('sep_conv_3x3', 1), ('sep_conv_5x5', 2), ('skip_connect', 0), ('sep_conv_5x5', 2), ('sep_conv_3x3', 0), ('sep_conv_5x5', 3)], [('sep_conv_3x3', 0), ('sep_conv_3x3', 1), ('dil_conv_3x3', 0), ('sep_conv_5x5', 2), ('sep_conv_5x5', 2), ('skip_connect', 3), ('skip_connect', 2), ('dil_conv_5x5', 3)]]

model_dict = {'model_7_24_5': model_7_24_5,
              'model_score_77': model_score_77,
              'model_7_30': model_7_30,
              'model_7_31': model_7_31,
              'top_in_100': top_in_100,
              'top_in_10': top_in_10,
              'net_iamgenet': net_iamgenet,
              'net_meco': net_meco,
              'net_cifar100': net_cifar100,
              's1_model1': s1_model1,
              's2_model1': s2_model1,
              's3_model1': s3_model1,
              's4_model1': s4_model1,
              's5_model1': s5_model1
              }
