net_cifar10 = [[('dil_conv_5x5', 0), ('sep_conv_5x5', 1), ('sep_conv_3x3', 0), ('sep_conv_5x5', 2), ('sep_conv_3x3', 2),
              ('skip_connect', 3), ('dil_conv_5x5', 3), ('skip_connect', 4)],
             [('sep_conv_3x3', 0), ('skip_connect', 1), ('skip_connect', 1), ('sep_conv_5x5', 2), ('sep_conv_5x5', 2),
              ('dil_conv_5x5', 3), ('dil_conv_5x5', 2), ('dil_conv_5x5', 4)],
             [('dil_conv_5x5', 0), ('skip_connect', 1), ('skip_connect', 1), ('dil_conv_3x3', 2), ('sep_conv_3x3', 1),
              ('sep_conv_5x5', 2), ('sep_conv_5x5', 3), ('sep_conv_5x5', 4)],
             [('sep_conv_5x5', 0), ('skip_connect', 1), ('dil_conv_3x3', 0), ('skip_connect', 1), ('sep_conv_3x3', 1),
              ('sep_conv_3x3', 3), ('sep_conv_3x3', 3), ('dil_conv_5x5', 4)],
             [('sep_conv_3x3', 0), ('skip_connect', 1), ('dil_conv_5x5', 1), ('skip_connect', 2), ('dil_conv_5x5', 0),
              ('sep_conv_3x3', 3), ('dil_conv_5x5', 2), ('dil_conv_3x3', 3)],
             [('skip_connect', 0), ('sep_conv_5x5', 1), ('skip_connect', 0), ('dil_conv_3x3', 1), ('dil_conv_5x5', 1),
              ('sep_conv_3x3', 3), ('sep_conv_5x5', 2), ('sep_conv_5x5', 3)],
             [('skip_connect', 0), ('dil_conv_5x5', 1), ('dil_conv_3x3', 0), ('skip_connect', 2), ('dil_conv_3x3', 1),
              ('sep_conv_3x3', 2), ('dil_conv_3x3', 1), ('dil_conv_5x5', 3)],
             [('skip_connect', 0), ('sep_conv_3x3', 1), ('sep_conv_5x5', 0), ('skip_connect', 1), ('sep_conv_5x5', 1),
              ('sep_conv_5x5', 3), ('dil_conv_5x5', 1), ('dil_conv_3x3', 2)],
             [('sep_conv_5x5', 0), ('skip_connect', 1), ('skip_connect', 0), ('sep_conv_5x5', 2), ('dil_conv_5x5', 2),
              ('dil_conv_5x5', 3), ('dil_conv_5x5', 0), ('sep_conv_5x5', 1)],
             [('sep_conv_5x5', 0), ('skip_connect', 1), ('sep_conv_3x3', 0), ('skip_connect', 2), ('sep_conv_5x5', 0),
              ('dil_conv_3x3', 1), ('dil_conv_5x5', 1), ('sep_conv_3x3', 2)],
             [('skip_connect', 0), ('sep_conv_3x3', 1), ('skip_connect', 0), ('dil_conv_5x5', 2), ('sep_conv_5x5', 1),
              ('dil_conv_5x5', 2), ('sep_conv_3x3', 1), ('dil_conv_5x5', 2)],
             [('dil_conv_3x3', 0), ('skip_connect', 1), ('dil_conv_3x3', 0), ('skip_connect', 2), ('sep_conv_3x3', 1),
              ('sep_conv_5x5', 3), ('dil_conv_5x5', 1), ('dil_conv_5x5', 3)],
             [('skip_connect', 0), ('dil_conv_5x5', 1), ('skip_connect', 0), ('dil_conv_3x3', 1), ('sep_conv_5x5', 1),
              ('sep_conv_3x3', 3), ('sep_conv_5x5', 1), ('dil_conv_3x3', 4)],
             [('sep_conv_5x5', 0), ('skip_connect', 1), ('sep_conv_3x3', 0), ('skip_connect', 2), ('sep_conv_3x3', 0),
              ('sep_conv_5x5', 1), ('dil_conv_3x3', 1), ('dil_conv_5x5', 4)],
             [('skip_connect', 0), ('sep_conv_5x5', 1), ('dil_conv_3x3', 0), ('skip_connect', 1), ('dil_conv_3x3', 1),
              ('sep_conv_5x5', 2), ('dil_conv_5x5', 0), ('dil_conv_5x5', 2)],
             [('skip_connect', 0), ('sep_conv_3x3', 1), ('skip_connect', 0), ('sep_conv_3x3', 1), ('dil_conv_5x5', 0),
              ('sep_conv_3x3', 2), ('sep_conv_5x5', 2), ('sep_conv_5x5', 3)],
             [('skip_connect', 0), ('dil_conv_3x3', 1), ('skip_connect', 1), ('sep_conv_5x5', 2), ('sep_conv_3x3', 0),
              ('dil_conv_3x3', 3), ('sep_conv_5x5', 1), ('dil_conv_3x3', 3)],
             [('skip_connect', 0), ('sep_conv_3x3', 1), ('dil_conv_3x3', 0), ('skip_connect', 2), ('sep_conv_5x5', 2),
              ('sep_conv_3x3', 3), ('sep_conv_5x5', 1), ('sep_conv_5x5', 3)],
             [('skip_connect', 0), ('sep_conv_3x3', 1), ('dil_conv_5x5', 1), ('skip_connect', 2), ('sep_conv_3x3', 1),
              ('sep_conv_3x3', 3), ('dil_conv_5x5', 1), ('sep_conv_5x5', 4)],
             [('skip_connect', 0), ('dil_conv_5x5', 1), ('dil_conv_3x3', 0), ('skip_connect', 2), ('sep_conv_3x3', 1),
              ('sep_conv_3x3', 3), ('sep_conv_5x5', 2), ('sep_conv_3x3', 3)]]

net_cifar100 = [
    [('max_pool_3x3', 0), ('max_pool_3x3', 1), ('max_pool_3x3', 1), ('skip_connect', 2), ('max_pool_3x3', 0),
     ('skip_connect', 3), ('max_pool_3x3', 0), ('max_pool_3x3', 1)],
    [('skip_connect', 0), ('sep_conv_3x3', 1), ('max_pool_3x3', 0), ('max_pool_3x3', 2), ('max_pool_3x3', 0),
     ('skip_connect', 3), ('max_pool_3x3', 0), ('max_pool_3x3', 3)],
    [('skip_connect', 0), ('dil_conv_5x5', 1), ('skip_connect', 1), ('max_pool_3x3', 2), ('max_pool_3x3', 2),
     ('max_pool_3x3', 3), ('skip_connect', 2), ('max_pool_3x3', 3)],
    [('max_pool_3x3', 0), ('max_pool_3x3', 1), ('sep_conv_3x3', 1), ('skip_connect', 2), ('skip_connect', 2),
     ('max_pool_3x3', 3), ('skip_connect', 3), ('avg_pool_3x3', 4)],
    [('sep_conv_3x3', 0), ('dil_conv_3x3', 1), ('max_pool_3x3', 0), ('dil_conv_3x3', 2), ('skip_connect', 2),
     ('skip_connect', 3), ('dil_conv_5x5', 2), ('skip_connect', 4)],
    [('sep_conv_5x5', 0), ('max_pool_3x3', 1), ('sep_conv_3x3', 1), ('skip_connect', 2), ('sep_conv_5x5', 2),
     ('skip_connect', 3), ('skip_connect', 2), ('skip_connect', 4)],
    [('sep_conv_5x5', 0), ('dil_conv_5x5', 1), ('skip_connect', 1), ('skip_connect', 2), ('sep_conv_5x5', 2),
     ('skip_connect', 3), ('skip_connect', 3), ('skip_connect', 4)],
    [('sep_conv_5x5', 0), ('skip_connect', 1), ('sep_conv_5x5', 1), ('skip_connect', 2), ('dil_conv_3x3', 1),
     ('skip_connect', 3), ('sep_conv_3x3', 1), ('skip_connect', 3)],
    [('sep_conv_3x3', 0), ('skip_connect', 1), ('sep_conv_5x5', 1), ('dil_conv_3x3', 2), ('sep_conv_5x5', 1),
     ('sep_conv_3x3', 2), ('skip_connect', 3), ('skip_connect', 4)],
    [('dil_conv_3x3', 0), ('skip_connect', 1), ('sep_conv_5x5', 1), ('skip_connect', 2), ('skip_connect', 1),
     ('skip_connect', 2), ('skip_connect', 3), ('skip_connect', 4)],
    [('skip_connect', 0), ('sep_conv_3x3', 1), ('skip_connect', 0), ('skip_connect', 2), ('skip_connect', 2),
     ('skip_connect', 3), ('skip_connect', 2), ('skip_connect', 3)],
    [('sep_conv_5x5', 0), ('sep_conv_5x5', 1), ('max_pool_3x3', 1), ('skip_connect', 2), ('sep_conv_5x5', 1),
     ('skip_connect', 3), ('skip_connect', 3), ('skip_connect', 4)],
    [('sep_conv_5x5', 0), ('skip_connect', 1), ('sep_conv_5x5', 1), ('skip_connect', 2), ('skip_connect', 1),
     ('dil_conv_3x3', 2), ('skip_connect', 3), ('skip_connect', 4)],
    [('dil_conv_3x3', 0), ('sep_conv_3x3', 1), ('sep_conv_5x5', 0), ('dil_conv_3x3', 2), ('sep_conv_5x5', 0),
     ('sep_conv_5x5', 2), ('dil_conv_3x3', 2), ('skip_connect', 4)],
    [('skip_connect', 0), ('skip_connect', 1), ('dil_conv_3x3', 0), ('dil_conv_5x5', 2), ('skip_connect', 1),
     ('dil_conv_3x3', 2), ('dil_conv_5x5', 1), ('dil_conv_5x5', 2)],
    [('sep_conv_3x3', 0), ('skip_connect', 1), ('skip_connect', 0), ('skip_connect', 2), ('sep_conv_3x3', 0),
     ('skip_connect', 2), ('dil_conv_5x5', 0), ('sep_conv_3x3', 3)],
    [('dil_conv_3x3', 0), ('sep_conv_5x5', 1), ('sep_conv_5x5', 1), ('dil_conv_3x3', 2), ('skip_connect', 0),
     ('dil_conv_5x5', 1), ('dil_conv_5x5', 3), ('sep_conv_3x3', 4)],
    [('skip_connect', 0), ('skip_connect', 1), ('sep_conv_3x3', 1), ('skip_connect', 2), ('sep_conv_5x5', 1),
     ('skip_connect', 3), ('skip_connect', 0), ('sep_conv_3x3', 4)],
    [('sep_conv_3x3', 0), ('skip_connect', 1), ('sep_conv_3x3', 1), ('dil_conv_3x3', 2), ('sep_conv_5x5', 0),
     ('skip_connect', 1), ('skip_connect', 0), ('dil_conv_3x3', 1)],
    [('sep_conv_3x3', 0), ('skip_connect', 1), ('sep_conv_3x3', 0), ('skip_connect', 2), ('sep_conv_5x5', 0),
     ('sep_conv_5x5', 2), ('sep_conv_3x3', 1), ('sep_conv_5x5', 4)]]

model_dict = {
    'net_cifar10': net_cifar10,
    'net_cifar100': net_cifar100
}
